name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main # Change this to your main branch

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 14

            - name: Install dependencies
              run: npm ci

            - name: Build Astro.js website
              run: npm run build # Adjust the build command based on your project setup

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist # Adjust the publish directory based on your project setup
